### ISSUE TITLE
Change JSON format

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#121]
```json
{"fields":[
    {"name":"012A/00", "subfields":[
        {"name":"A","value":"B"},
        ...
    ] },
    ...
]}
```

**TODOs**
- [x] Rename subfield `code` to `name` (see #129)
- [x] Add `fields` key
- [x] Rename field `tag` to `name`
