### ISSUE TITLE
Pica Release 0.1.0

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#149]
- [x] Move PICA+ parser into separate crate (use `bstr::BStr` instead of `&str`)
- [ ] Move path parser into separate crate
- [ ] Move PICA+ filter into separate crate (rename to matcher)
- [ ] Add `slice` command (#98)
- [ ] Add `index` command (#56)
- [ ] Change JSON format (#121)
- [ ] Setup release workflow (#114)
- [ ] Publish project to crates.io (#118)
