### ISSUE TITLE
Roadmap 2022

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#358]
This is the tracking issue for the main goals in 2022; feel free to drop your wishes and ideas as comments.

# Stabilize Beta-Commands

The main goal in 2022 is to stabilize the set of beta-commands:

- consolidated cli arguments across commands (and external tools)
- description and examples via `--help`

# Linter Command

- first prototypical implementation of a `linter` command

# Documentation

- Tutorial: Working with pica-rs and Makefiles
- Clean-up README (see https://skerritt.blog/make-popular-open-source-projects/)
- code{4}lib article?

## User Guide (in german)

- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/407
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/412
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/415
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/420
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/500

# Testing

- Increase test coverage (>= 98%)
- Internal test suite (on a larger scale)
- Property based testing with quickcheck
- Benchmarks (comparison with other tools)

# Internal Improvements

- After GATs (generic associated types) are available in Rust, implement the record iterator as an `LendingIterator` (see https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html)
- Rust API guideline conformance (https://rust-lang.github.io/api-guidelines/)

# Misc

- #118

**Comment by nichtich** [comment]
I think #118 should be part of the roadmap.

**Comment by niko2342** [comment]
Development progress has been much slower than expected in 2022. I've moved all relevant items into to Roadmap for 2023: see https://github.com/deutsche-nationalbibliothek/pica-rs/issues/505.
