### ISSUE TITLE
Transliteration between unicode normal forms (NFC, NFD, NFKC, NFKD)

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#400]
Tracking issue for transliteration between unicode normal forms (NFC, NFD, NFKC, NFKD):

### TODO

- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/399
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/401
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/402
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/403
- [x] https://github.com/deutsche-nationalbibliothek/pica-rs/pull/404
