### ISSUE TITLE
Roadmap 2023

### ISSUE THREAD

**Issue by nwagner84** [deutsche-nationalbibliothek/pica-rs#505]
This is the tracking issue for the main goals in 2023; feel free to drop your wishes and ideas as comments.

# Command Stabilization

* [x] #507 
* [x] #508
* [x] #509
* [x] #510
* [x] #511
* [x] #506
* [x] #512
* [x] #513
* [x] #514
* [x] #515
* [x] #517
* [x] #516
* [x] #518 (depricated)
* [x] #519 (depricated)

(Review #274)

# Internals

* [x] Move filter/matcher package into separate crate `pica-matcher`
* [ ] #366 

# Documentation

* [x] #458 
* [ ] #371 
* [ ] New Tutorial: Working with pica-rs and Makefiles
* [x] [Cleanup README](https://skerritt.blog/make-popular-open-source-projects/)
* [ ] Cleanup/Complete documentation

# Miscellaneous

* [ ] #118
